### PR TITLE
Set proper surname of @ladyleet

### PR DESCRIPTION
**Pull request by piecioshka**

### CODE REVIEW

**Comment by piecioshka** [comment]
cc: @ladyleet

**Comment by ladyleet** [comment]
Lgtm

**Comment by piecioshka** [comment]
Ping @siddharthkp

**Comment by siddharthkp** [comment]
Never too late to merge it, I guess 😅 

Thanks!

**Comment by siddharthkp** [comment]
Can't merge this PR anymore so updated it myself in https://github.com/siddharthkp/react-amsterdam-videos/commit/2b243a69927f896b68545c905c76500ac3477fc2

**Pull request closed without merging**
